Repository AnguseZhang/MatMaster, pull requests merged in 2025-09, with the labels that each got.

#149 chore: update GitHub Actions to streamline auto-labeling PRs by enhan…
  .github/workflows/pr-auto-label.yml
Labels: chore

#152 docs: clarify user interaction and fix task label for consistent documentation
  .github/workflows/pr-auto-label.yml
  agents/matmaster_agent/prompt.py
Labels: documentation

#156 feat: add evaluation module and streamline multi-turn evaluation components
  .github/workflows/pr-auto-label.yml
  .gitignore
  evaluate/base.py
  evaluate/base/__init__.py
  evaluate/base/evaluation.py
  evaluate/base/human_simulator.py
  evaluate/experiments/multi_turn/__init__.py
  evaluate/experiments/multi_turn/multi_turn_answer_exp.py
  evaluate/experiments/single_turn/__init__.py
  evaluate/experiments/single_turn/answer_qa_exp.json
  evaluate/experiments/single_turn/answer_qa_exp.py
  evaluate/experiments/single_turn/multi_options_exp.py
  evaluate/experiments/single_turn/transfer_or_answer_exp.py
  evaluate/experiments/single_turn/transfer_to_agent_exp.py
  evaluate/experiments/threads/__init__.py
  evaluate/experiments/threads/database_search/__init__.py
  evaluate/experiments/threads/database_search/database_search.json
  evaluate/experiments/threads/database_search/database_search.py
  evaluate/experiments/threads/structure_generate/__init__.py
  evaluate/experiments/threads/structure_generate/structure_generate.json
  evaluate/experiments/threads/structure_generate/structure_generate.py
  evaluate_simhuman/exp/database_search/database_search.py
  evaluate_simhuman/exp/database_search/evaluation_results.json
  evaluate_simhuman/exp/structure_generate/evaluation_results.json
  evaluate_simhuman/exp/structure_generate/structure_generate.py
  evaluate_threads/CHANGES.md
  evaluate_threads/README.md
  evaluate_threads/human_simulator.py
  evaluate_threads/test_human_simulator.py
  pyproject.toml
  uv.lock
Labels: feature

#160 refactor: add auto-label mapping for refactor and improve script modularity
  .github/workflows/pr-auto-label.yml
  evaluate/base/evaluation.py
  evaluate/experiments/threads/database_search/run.sh
  evaluate/experiments/threads/run.sh
Labels: maintenance

#161 fix: update google-adk dependency to include a2a extra and bump versi…
  pyproject.toml
  uv.lock
Labels: bug

#162 feat: enhance MatMasterAgent with job status monitoring, language callback, and code style unification
  agents/matmaster_agent/agent.py
  agents/matmaster_agent/base_agents/callback.py
  agents/matmaster_agent/base_agents/job_agent.py
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/constant.py
  agents/matmaster_agent/model.py
  agents/matmaster_agent/utils/job_utils.py
Labels: feature

#165 fix: quote consistency and LLM response ordering in callback
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/main.py
Labels: bug

#171 fix: Update prompts of ABACUS subagent
  agents/matmaster_agent/ABACUS_agent/agent.py
  agents/matmaster_agent/ABACUS_agent/constant.py
  agents/matmaster_agent/ABACUS_agent/prompt.py
Labels: bug

#172 fix: reduce hallucination and support multiple requests even though d…
  agents/matmaster_agent/MrDice_agent/openlam_agent/prompt.py
  agents/matmaster_agent/MrDice_agent/prompt.py
  agents/matmaster_agent/optimade_database_agent/__init__.py
  agents/matmaster_agent/optimade_database_agent/agent.py
  agents/matmaster_agent/optimade_database_agent/constant.py
  agents/matmaster_agent/optimade_database_agent/prompt.py
Labels: bug

#173 feat: implement async job status fetching in matmaster_agent using ai…
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/utils/job_utils.py
Labels: feature

#177 feat: add enhanced logging, reasoning tracking, and code optimization
  agents/matmaster_agent/base_agents/job_agent.py
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/model.py
  agents/matmaster_agent/prompt.py
  agents/matmaster_agent/utils/event_utils.py
Labels: feature

#179 fix: Update image and executor for ABACUS_calculation_agent
  agents/matmaster_agent/ABACUS_agent/constant.py
Labels: bug

#180 fix: Update image running ABACUS calculation
  agents/matmaster_agent/ABACUS_agent/constant.py
Labels: bug

#182 chore: update GitHub Actions workflow to use GITHUB_TOKEN and re-enab…
  .github/workflows/pr-auto-label.yml
  agents/matmaster_agent/structure_generate_agent/agent.py
Labels: chore

#184 fix: enhanced doc format process
  agents/matmaster_agent/document_parser_agent/agent.py
  agents/matmaster_agent/document_parser_agent/callback.py
Labels: bug

#195 refactor: update API configuration and constants for improved compatibility
  agents/matmaster_agent/base_agents/callback.py
  agents/matmaster_agent/base_agents/job_agent.py
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/constant.py
  agents/matmaster_agent/model.py
  agents/matmaster_agent/prompt.py
  agents/matmaster_agent/structure_generate_agent/agent.py
  agents/matmaster_agent/structure_generate_agent/constant.py
Labels: maintenance

#199 feat: Mr-Dice_v0.82 add Mofdb agent
  agents/matmaster_agent/MrDice_agent/agent.py
  agents/matmaster_agent/MrDice_agent/bohriumpublic_agent/constant.py
  agents/matmaster_agent/MrDice_agent/mofdb_agent/agent.py
  agents/matmaster_agent/MrDice_agent/mofdb_agent/constant.py
  agents/matmaster_agent/MrDice_agent/mofdb_agent/prompt.py
  agents/matmaster_agent/MrDice_agent/openlam_agent/constant.py
  agents/matmaster_agent/MrDice_agent/optimade_agent/constant.py
  agents/matmaster_agent/MrDice_agent/prompt.py
Labels: feature

#200 feat: add machine dpa invar
  agents/matmaster_agent/DPACalculator_agent/constant.py
  agents/matmaster_agent/INVAR_agent/constant.py
  agents/matmaster_agent/structure_generate_agent/constant.py
Labels: feature

#203 chore: switch dev machine sse link
  agents/matmaster_agent/INVAR_agent/constant.py
Labels: chore

#205 feat: add logging for origin_job_id, executor, and status in ResultCa…
  agents/matmaster_agent/base_agents/job_agent.py
Labels: feature

#206 chore: fix sse link of invar
  agents/matmaster_agent/INVAR_agent/constant.py
Labels: chore

#208 feat: update machine type and mcp url for sandbox
  agents/matmaster_agent/superconductor_agent/agent.py
  agents/matmaster_agent/superconductor_agent/constant.py
  agents/matmaster_agent/thermoelectric_agent/agent.py
  agents/matmaster_agent/thermoelectric_agent/constant.py
Labels: feature

#209 feat: add mat inform parsing
  agents/matmaster_agent/prompt.py
  agents/matmaster_agent/structure_generate_agent/agent.py
  agents/matmaster_agent/structure_generate_agent/prompt.py
Labels: feature

#217 feat: enhance `get_acs_result.py` with job duration calculation and i…
  .gitignore
  scripts/get_acs_result.py
Labels: feature

#216 feat: APEX change cluster to acs for test
  agents/matmaster_agent/apex_agent/constant.py
Labels: feature

#219 fix: add check for response content to handle LLM completion errors s…
  agents/matmaster_agent/public/callback.py
Labels: bug

#220 fix: change Apex image for test env
  agents/matmaster_agent/apex_agent/constant.py
Labels: bug

#221 feat: add optional download flag for conditional file download in script
  scripts/get_acs_result.py
Labels: feature

#222 refactor: extract token retrieval and file download logic into reusab…
  .gitignore
  scripts/get_acs_result.py
Labels: maintenance

#223 feat: integrate jsonpickle to log results and remove temporary file a…
  .gitignore
  scripts/get_acs_result.py
Labels: feature

#225 refactor: use pathlib for file existence check and update error loggi…
  scripts/get_acs_result.py
Labels: maintenance

#226 fix: combine test and prod env
  agents/matmaster_agent/apex_agent/constant.py
Labels: bug

#229 refactor: streamline job handling and remove unused attributes
  agents/matmaster_agent/base_agents/callback.py
  agents/matmaster_agent/base_agents/job_agent.py
  agents/matmaster_agent/callback.py
  agents/matmaster_agent/main.py
  agents/matmaster_agent/model.py
  agents/matmaster_agent/utils/job_utils.py
  agents/matmaster_agent/utils/tool_response_utils.py
Labels: maintenance
